### ISSUE TITLE
cli: dbnet exec  output as CSV or JSON to screen or file ?

### ISSUE THREAD

**Issue by gedw99** [dbnet-io/dbnet#9]
At the moment i can't seem to run SQL and get an output to terminal of the actual data.

Whats your game plan / roadmap here if i may ask ?

here is my little test case: 

```sh
dbnet exec SQLITE --file select.sql
2023-07-10 16:06:44 INF Executing...
2023-07-10 16:06:44 INF Successful! Duration: 0 seconds
```

select-sql is simply:
```sql
SELECT * FROM positions;
```

The CLI help does not show any way to add args to tell it i want CSV or JSON out to screen or file....

```sh
dbnet exec -h
exec - execute a SQL query

  Usage:
    exec [conn]

  Positional Variables: 
    conn   The connection name (Required)
  Flags: 
       --version   Displays the program version string.
    -h --help      Displays help with available flag, subcommand, and positional value parameters.
       --query     The SQL query to execute
       --file      The SQL file to execute

```

**Comment by flarco** [comment]
Ah interesting, the `exec` sub-command was simply to execute SQLs without results (like updates). But I can add that. I usually use [sling](https://github.com/slingdata-io/sling-cli) for that with `sling run --src-conn SQLITE --src-stream 'select * from positions' --stdout`. Sling will detect your env connections as well the same way.

But makes sense to actually output the results as CSV or JSON from CLI. Will add that as well.

For now you can do that with sling or from the frontend, there is a button on the right side, that says `Export to CSV`. 
<img width="403" alt="image" src="https://github.com/dbnet-io/dbnet/assets/7671010/5ddeb48f-d8b4-4abc-9c9a-c96795697187">

**Comment by flarco** [comment]
This is done. Feel free to try it!

```
$ ./dbnet exec
exec - execute a SQL query

  Usage:
    exec [conn]

  Positional Variables: 
    conn   The connection name (Required)
  Flags: 
       --version   Displays the program version string.
    -h --help      Displays help with available flag, subcommand, and positional value parameters.
       --query     The SQL query to execute
       --file      The SQL file to execute
       --csv       Output the results as CSV
       --json      Output the results as JSON Lines
```

**Comment by gedw99** [comment]
Thanks @flarco 

will try it .
